### ISSUE TITLE
Make Data Files

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugphyzzExports#1]
@kbeckenrode @lwaldron Do we already have a function that generates exports or the data?

**Comment by lwaldron** [comment]
Yes, if it's not clear from the vignette we need to improve the documentation. IIRC the function is called bugphyzz().

**Comment by jwokaty** [comment]
We'll follow the BugSigDBExports model, where we have a `gmt` files for each physiology for species and genus with ncbi and taxnames--i.e., species ncbi, species taxnames, genus ncbi, and genus taxnames. We should also have a "full.csv" for each physiology. Files should also have the date and license at the top of the gmt file.

**Comment by jwokaty** [comment]
@lwaldron I'd like to discuss this at our meeting tomorrow. When we want a signature that has the genus (with either the tax name or ncbi id), we want ~~`Parent_rank == 'genus'` or this is where~~ `rank` == `genus`?
