### ISSUE TITLE
COGEM pathogenicity rating does not need a range

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzzExports#11]
@kbeckenrode. @jwokaty, I don't think COGEM pathogenicity rating needs a range since the rating corresponds to discrete categories (classes 1, 2, 3, and 4; [source](https://docs.google.com/spreadsheets/d/1MM7unEZzwfjllFGzFScV9T1gAQxBXbu03ZmozGczKIw/edit#gid=0)).

I think this thresholding would mix categories 1 and 2: https://github.com/waldronlab/bugphyzzExports/blob/5a8a354355c47aa4c32ecbd427deec13fec9e411/inst/scripts/export_bugphyzz.R#L24-L28

Actually, I think the attribute values would fit better as 'class 1', 'class 2', 'class 3', and 'class 4' (we don't have any in class 4).

**Comment by jwokaty** [comment]
I'm going to transfer this issue to bugphyzzExports since the change should happen there.

**Comment by kbeckenrode** [comment]
This is true. This is not a range.
