### ISSUE TITLE
avoid silently dropping data

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bugphyzzExports#23]
There are a couple `keep` lines that appear that they would silently drop data not matching certain rules. Any such dropping should produce warnings in the logs.

https://github.com/waldronlab/bugphyzzExports/blob/a9fc18914cb3b1d9ea3a3d1c0121ccac5c8d482a/inst/scripts/export_bugphyzz.R#L81

**Comment by sdgamboa** [comment]
This has been addressed in the log_file.log.
