### ISSUE TITLE
Set devel as default

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugphyzzExports#41]
I think somewhere we should have switched to devel then switched to main. Wait to resolve this after merging the sdgamboa/update-workflows branch.

**Comment by sdgamboa** [comment]
I think this PR #47 should be merged instead. Thinking about just deleting "sdgamboa/update-workflows"

**Comment by jwokaty** [comment]
The previous issue was resolved by merging #47 so I'll use this to rename main to devel.
