### ISSUE TITLE
no `ltp3` on sdgamboa/update-workflow branch

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugphyzzExports#45]
@sdgamboa Should https://github.com/waldronlab/bugphyzzExports/tree/sdgamboa/update-workflow be merged? I think I can fix the installing dependencies with https://github.com/jwokaty/bugphyzzExports/blob/0ccfeb6e89765de41c52741c95109eb4055c4fad/.github/workflows/export-bugphyzz.yml#L22-L35; however, I'm running into another issue, which is that there's no function `ltp3` in https://github.com/waldronlab/bugphyzzExports/blob/e8fed8f333b7c378e4996999499acf8ce356c740/inst/scripts/export_bugphyzz.R#L273. I copied the export_bugphyzz.R from your branch to a test branch in my repo so I could run the GitHub Action Workflow, which has the error https://github.com/jwokaty/bugphyzzExports/actions/runs/7331443622/job/19964080731#step:6:317. It might be easier to work out these issues if `sdgamboa/update-workflow` is merged, but maybe it shouldn't contain the generated files as it makes the commits quite large (it takes awhile for me to `git pull` your branch).

**Comment by sdgamboa** [comment]
I think I could merge it. There will be a few more modifications. I'll remove the files from the branch.
