### ISSUE TITLE
Release not showing on Zenodo

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzzExports#57]
I made a few adjustments to the json file and created a pre-release.

+ I converted the license from an array to a string based on this issue: https://github.com/zenodo/zenodo/issues/2515

+ I fixed a duplicated name in the json file.

Maybe this would help start processing the files on Zenodo. @jwokaty, I was wondering if you could check if the Zenodo release is still failing.

**Comment by jwokaty** [comment]
Nice, it looks like it is showing now: https://zenodo.org/records/10980813

**Comment by sdgamboa** [comment]
Great, thanks!
